#!/bin/bash

if [ -z "${1}" ] || [ "${1}" == "master" ]; then
  VERSION="master"
  GITHUB_REF="heads/${VERSION}"
else
  VERSION="release-${1}"
  GITHUB_REF="tags/${VERSION}"
fi

./deps_delivery "${1}" && \
wget -O nginx.tar.gz "https://github.com/nginx/nginx/archive/refs/${GITHUB_REF}.tar.gz" && \
tar xf nginx.tar.gz && cd "nginx-${VERSION}" && \
./auto/configure \
  --with-pcre=../deps/pcre \
  --with-zlib=../deps/zlib \
  --with-openssl=../deps/openssl \
  --with-http_ssl_module && make install -j4
